Stat:=
{
	NrFilesDownloaded:0,
	NrErrors:0
};

Binary:=Utf8Encode("Hello").GetType();
ws:=Waher.Content.Xml.XML.WriterSettings(true,true);
LinkUri:=null;

DownloadFiles(PageUrl,DownloadFolder,CheckExtension):=
(
	preview("Downloading: "+PageUrl);
	PageUrl:=Create(System.Uri,PageUrl);
	Page:=GET(PageUrl,{Accept:"text/html"});

	sb:=Create(System.Text.StringBuilder);
	w:=System.Xml.XmlWriter.Create(sb,ws);
	Page.Export(w);
	w.Flush();
	x:=Xml(sb.ToString());
	Links:=[foreach Node in x.SelectNodes("//A/@href") do Node.Value];

	
	foreach Link in Links do
	(
		Extension:=LowerCase(System.IO.Path.GetExtension(Link));

		if (!CheckExtension or Extension=".cer" or Extension=".pem" or Extension=".crt") and
		    System.Uri.TryCreate(Link,System.UriKind.RelativeOrAbsolute,LinkUri) and 
		    !LinkUri.IsAbsoluteUri and
		    System.Uri.TryCreate(PageUrl,LinkUri,LinkUri) then
		(
			try
			(
				preview("Downloading: "+Str(LinkUri));
				Content:=Get(LinkUri);
				if Content is Binary then
				(
					FileName:=System.IO.Path.GetFileName(Link);
					FileName:=System.IO.Path.Combine(DownloadFolder,FileName);
					SaveFile(Content,FileName);
					Stat.NrFilesDownloaded++;
				)
			)
			catch
			(
				printline("Error ("+Link+"): "+Exception.Message);
				Stat.NrErrors++;
			)
		)
	)
);

PrintStat():=
(
	printline("Nr Files Downloaded: "+Stat.NrFilesDownloaded);
	printline("Nr Errors: "+Stat.NrErrors);
);

ZeroStat():=
(
	Stat.NrFilesDownloaded:=0;
	Stat.NrErrors:=0;
);

//DownloadFiles("https://www.passports.gov.au/help/australian-country-signing-certificate-authority-csca","C:\\My Projects\\IcaoPkiCertificates\\Manual\\AU",true);
//DownloadFiles("https://www.iddeea.gov.ba/en/pki-system-for-digital-signing-of-travel-documents-and-e-ids/","C:\\My Projects\\IcaoPkiCertificates\\Manual\\BA",false);
//DownloadFiles("https://csca.crmd.moi.gov.cy/PKI/CSCA/Root_Certificate","C:\\My Projects\\IcaoPkiCertificates\\Manual\\CY",false);

DownloadFiles("https://www.bmi.gv.at/downloads/csca.html","C:\\My Projects\\IcaoPkiCertificates\\Manual\\AT",true);
DownloadFiles("https://certs.eid.belgium.be/","C:\\My Projects\\IcaoPkiCertificates\\Manual\\BE",true);	// NOTE: Certificates available in PDF files also. These are not downloaded
DownloadFiles("https://www.bmi.gv.at/downloads/csca.html","C:\\My Projects\\IcaoPkiCertificates\\Manual\\AT",true);

PrintStat();