Stat:=
{
	NrFilesDownloaded:0,
	NrErrors:0
};

Binary:=Utf8Encode("Hello").GetType();
ws:=Waher.Content.Xml.XML.WriterSettings(true,true);
LinkUri:=null;

DownloadFiles(PageUrl,DownloadFolder):=
(
	preview(printline("Downloading: "+PageUrl));
	PageUrl:=Create(System.Uri,PageUrl);
	Page:=GET(PageUrl,{Accept:"text/html"});
	preview(printline("Downloaded."));

	sb:=Create(System.Text.StringBuilder);
	w:=System.Xml.XmlWriter.Create(sb,ws);
	Page.Export(w);
	w.Flush();
	x:=Xml(sb.ToString());
	hs:=Create(System.Collections.Generic.HashSet,System.String);
	foreach Node in x.SelectNodes("//A/@href") do hs.Add(Node.Value);
	Links:=[foreach Link in hs : Link];
	preview(printline(Str(count(Links))+" unique links in document."));
	
	foreach Link in Links do
	(
		if !empty(Link) && Link!="#" && System.Uri.TryCreate(PageUrl,Link,LinkUri) then
		(
			try
			(
				preview(printline("Downloading: "+Str(LinkUri)));
				Content:=Get(LinkUri);
				FileName:=System.IO.Path.GetFileName(Link);
				FileName:=System.IO.Path.Combine(DownloadFolder,FileName);

				if Content is Binary then
				(
					SaveFile(Content,FileName);
					Stat.NrFilesDownloaded++;
				)
				else if Content is Waher.Content.Binary.CustomEncoding then
				(
					SaveFile(Content.Encoded,FileName);
					Stat.NrFilesDownloaded++;
				)
				else
					preview(printline("Type: "+Str(Content.GetType())));
			)
			catch
			(
				printline("Error ("+Link+"): "+Exception.Message);
				Stat.NrErrors++;
			)
		)
	);
	preview(printline("Links processed."));
);

PrintStat():=
(
	printline("Nr Files Downloaded: "+Stat.NrFilesDownloaded);
	printline("Nr Errors: "+Stat.NrErrors);
);

ZeroStat():=
(
	Stat.NrFilesDownloaded:=0;
	Stat.NrErrors:=0;
);

//DownloadFiles("https://www.passports.gov.au/help/australian-country-signing-certificate-authority-csca","C:\\My Projects\\IcaoPkiCertificates\\Manual\\AU");
//DownloadFiles("https://www.iddeea.gov.ba/en/pki-system-for-digital-signing-of-travel-documents-and-e-ids/","C:\\My Projects\\IcaoPkiCertificates\\Manual\\BA");
//DownloadFiles("https://csca.crmd.moi.gov.cy/PKI/CSCA/Root_Certificate","C:\\My Projects\\IcaoPkiCertificates\\Manual\\CY");
//DownloadFiles("https://archiv.mv.gov.cz/mvcren/article/csca-certificates-108056.aspx","C:\\My Projects\\IcaoPkiCertificates\\Manual\\CZ");
//DownloadFiles("https://politi.dk/en/law-and-information/the-danish-country-signing-ca-csca","C:\\My Projects\\IcaoPkiCertificates\\Manual\\DK");
//DownloadFiles("https://ants.gouv.fr/csca","C:\\My Projects\\IcaoPkiCertificates\\Manual\\FR");
//DownloadFiles("https://poliisi.fi/en/csca","C:\\My Projects\\IcaoPkiCertificates\\Manual\\FI");



DownloadFiles("https://www.bmi.gv.at/downloads/csca.html","C:\\My Projects\\IcaoPkiCertificates\\Manual\\AT");
DownloadFiles("https://certs.eid.belgium.be/","C:\\My Projects\\IcaoPkiCertificates\\Manual\\BE");	// NOTE: Certificates available in PDF files also. These are not downloaded
DownloadFiles("https://www.mvr.bg/en/ministry/about-ministry-of-internals/usefull-for-you/certificates-for-verification-of-e-documents","C:\\My Projects\\IcaoPkiCertificates\\Manual\\BG");
DownloadFiles("https://pki.politsei.ee/","C:\\My Projects\\IcaoPkiCertificates\\Manual\\EE");

PrintStat();